spring:
  application:
    name: user-management-service

  datasource:
    url: jdbc:mysql://localhost:3306/ecom
    username: root
    password: password
    hikari:
      auto-commit: true
      minimum-idle: 1
logging:
  level:
    org:
      springframework:
        jdbc: TRACE